### ISSUE TITLE
Bookmarklet fails when the current page is an image

### ISSUE THREAD

**Issue by mechanical-snail** [jarred/src-img#8]
In Firefox 3.6, if the current page is an image (e.g. `http://upload.wikimedia.org/wikipedia/commons/3/3b/Gato_enervado_pola_presencia_dun_can.jpg`), clicking the bookmarklet apparently does nothing. The error logged in the console is

```
Error: uncaught exception: [Exception... "Node cannot be inserted at the specified point in the hierarchy"  code: "3" nsresult: "0x80530003 (NS_ERROR_DOM_HIERARCHY_REQUEST_ERR)"  location: "http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.min.js Line: 4"]
```

It would make sense to detect this case, and go directly to the Google reverse image search page.

**Comment by hydnhntr** [comment]
Firefox 3.6 is 8 major releases behind and 2 years old. The error looks like a browser issue not being able to add elements to the DOM (there isn't one as it's just an image). 

While FF 3.6 is 10% of total Firefox users, because of the relative age of the browser and type of error I don't think it's worth our attention.
